-- 코드를 작성해주세요
SELECT C.ID
FROM (
    SELECT * FROM ECOLI_DATA WHERE PARENT_ID IS NULL) A
    INNER JOIN ECOLI_DATA B ON A.ID = B.PARENT_ID
    INNER JOIN ECOLI_DATA C ON B.ID = C.PARENT_ID
ORDER BY C.ID