SELECT CHILD.ID, CHILD.GENOTYPE, PARENT.GENOTYPE as PARENT_GENOTYPE
FROM ECOLI_DATA CHILD, ECOLI_DATA PARENT
WHERE CHILD.PARENT_ID = PARENT.ID AND CHILD.GENOTYPE & PARENT.GENOTYPE = PARENT.GENOTYPE
ORDER BY CHILD.ID